---
default:
  image: docker:24.0.5

stages:
  - quality
  - build

quality:
  stage: phpstan
  script:
    - echo “php-cs-fixer”
  stage: cs-fixer
  script:
    - echo "phpstan"

build:
  stage: build
  script:
    - echo "build"
