---
default:
  image: docker:24.0.5

stages:
  - quality
  - cs-fixer
  - build

quality:
  stage: quality
  script:
    - echo “phpstan”

cs-fixer:
  stage: cs-fixer
  script:
    - echo "php-cs-fixer"

build:
  stage: build
  script:
    - echo "build"
