---
default:
  image: docker:24.0.5

stages:
  - quality
  - build

phpstan:
  stage: quality
  script:
    - echo “php-cs-fixer”
    - echo "phpstan"

build:
  stage: build
  script:
    - echo "build"
