services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html

  db:
    image: mysql:5.7
    env_file:
      - .env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PMA_HOST: db

volumes:
  db-data: